# Generated by Django 5.2.8 on 2025-12-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('song', 'user', 'room')},
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['room'], name='Room_vote_room_id_8d3a39_idx'),
        ),
    ]
