# Generated by Django 5.2.8 on 2025-12-09 13:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0003_alter_song_options_song_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={},
        ),
        migrations.AddField(
            model_name='song',
            name='played_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vote',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='Room.song'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('song', 'user')},
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['video_id'], name='Room_song_video_i_418fdc_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['room', 'played_at'], name='Room_song_room_id_1f3e85_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['song'], name='Room_vote_song_id_3be525_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['user'], name='Room_vote_user_id_01d78b_idx'),
        ),
    ]
